### ISSUE TITLE
What value of ambient light intensity do we use?

### ISSUE THREAD

**Issue by velociraptor111** [alecjacobson/computer-graphics-ray-tracing#1]
I can see that we are given the ambient coefficient (Ka) for a material. But what value of ambient light intensity are we supposed to use ?  I cannot find this anywhere on the code.

**Comment by alecjacobson** [comment]
let's just use white.

**Comment by wammies** [comment]
I find that if I use [1, 1, 1] as the ambient light intensity, the image looks very washed out (which I think makes sense, since the Ka of the materials is the same as the Kd and the ambient light would therefore be the brightest light in the scene). However, if I omit the ambient term I get a result that looks exactly like the image in the readme. Should we use a lower value for the ambient light?

**Comment by abhimadan** [comment]
Yes, you're supposed to scale the ambient light by 0.1 (see https://github.com/alecjacobson/computer-graphics-ray-tracing/blob/master/include/blinn_phong_shading.h#L13).
